name: Unit-Test pipeline and publish results

on:
  workflow_dispatch:   # manual run
  pull_request:        # auto run only on PRs into main
    branches:
      - main

jobs:
  unit-tests-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests and generate JUnit XML
        run: |
          pytest --junitxml=report.xml || true

      - name: Parse test results
        id: parse
        run: |
          python scripts/parse_test_results.py
          # read the message content
          msg=$(cat slack_msg.txt)
          echo "slack_message<<EOF" >> $GITHUB_OUTPUT
          echo "$msg" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


      - name: Show Slack message (debug)
        run: cat slack_msg.txt

      - name: Verify Slack message
        run: test -s slack_msg.txt

      - name: Send Slack Notification
        if: always()
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Unit Test Results
          SLACK_MESSAGE: ${{ steps.parse.outputs.slack_message }}